spring:
  application:
    name: UserAuthService
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: nikhil
#      password: nikhil

  datasource:
    url: jdbc:postgresql://localhost:5432/hospitalerp
    username: postgres
    password: root

server:
  port: 8082